### PR TITLE
Do not drop index while reindexing products

### PR DESCRIPTION
**Pull request by pamil**

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
Please update README with this new command.

**Comment by pamil** [comment]
@pjedrzejewski it's here https://github.com/Sylius/SyliusElasticSearchPlugin/pull/56/files#diff-04c6e90faac2675aa89e2176d2eec7d8L1138

**Comment by pjedrzejewski** [comment]
👍 👍 👍 

@klederson This is the new command you should use. :)

**Comment by petrhamak** [comment]
Are you sure it works? While UpdateSimpleProducts worked well, UpdateProductIndexCommand nope.

$productDocuments = $this->productDocumentRepository->findDocuments($search);
is empty, so no index runs.

**Pull request merged**
